### ISSUE TITLE
Configure output does not match config.log

### ISSUE THREAD

**Issue by rennehan** [SWIFTSIM/SWIFT#40]
Hi, I noticed a mismatch between the ./configure output and the config.log output, relating to the HDF5 library.

I'm using HDF5(+MPI) 1.8.22 without specifying --with-hdf5 in the ./configure command. Configure finds the correct library with no issues, and the configure information gives:

>   HDF5 enabled         : yes
>           - parallel          : yes

During my run, I noticed that the snapshot time steps were taking ages. It turns out, config.log says that:

> HDF5_Type='serial'

That is odd, so I reconfigured by passing --with-hdf5=`which h5pcc` and that successfully made the two outputs match. I thought this was a bit misleading and should probably match. I'm not sure if the issue is reproducible or not at this time.

**Comment by pwdraper** [comment]
Hi @rennehan, this is the correct behaviour. The configure script just checks for an HDF5 initially (using `h5cc`), so that will report as a serial version, further checks then determine if the HDF5 library also supports MPI, at which time we change to parallel.

The result of all this is that the macro `HAVE_PARALLEL_HDF5`  will be defined or not. Check your `config.h` file
and see if this is working correctly without specifying the need to use `h5pcc`. If that doesn't help, can you attach the `config.log` file from the build you think is broken I can check to see what happened.
